# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado projects/constraint_file/example/Nexys-Video-Master.xdc

# Block Designs: bd/mainDesign/mainDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign || ORIG_REF_NAME==mainDesign} -quiet] -quiet

# IP: bd/mainDesign/ip/mainDesign_fifo_generator_0_0/mainDesign_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign_fifo_generator_0_0 || ORIG_REF_NAME==mainDesign_fifo_generator_0_0} -quiet] -quiet

# IP: bd/mainDesign/ip/mainDesign_core_wrapper_0_0/mainDesign_core_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign_core_wrapper_0_0 || ORIG_REF_NAME==mainDesign_core_wrapper_0_0} -quiet] -quiet

# IP: bd/mainDesign/ip/mainDesign_uart_tx_0_0/mainDesign_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign_uart_tx_0_0 || ORIG_REF_NAME==mainDesign_uart_tx_0_0} -quiet] -quiet

# IP: bd/mainDesign/ip/mainDesign_uart_rx_0_0/mainDesign_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign_uart_rx_0_0 || ORIG_REF_NAME==mainDesign_uart_rx_0_0} -quiet] -quiet

# IP: bd/mainDesign/ip/mainDesign_clk_wiz_0_0/mainDesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainDesign_clk_wiz_0_0 || ORIG_REF_NAME==mainDesign_clk_wiz_0_0} -quiet] -quiet

# XDC: d:/Vivado projects/weak_simulator/weak_simulator.gen/sources_1/bd/mainDesign/mainDesign_ooc.xdc
